// packages/web-components-vanilla/src/modal.ts
import { nextId, ControlLeaf, OpenController } from "./shared";

export const VANILLA_MODAL_TAG = "vanilla-modal";
export const VANILLA_MODAL_TRIGGER_TAG = "vanilla-modal-trigger";
export const VANILLA_MODAL_POPUP_TAG = "vanilla-modal-popup";
export const VANILLA_MODAL_CLOSE_TAG = "vanilla-modal-close";
export class VanillaModalTriggerElement extends ControlLeaf {
  static override marker = "modal-trigger";
}
export class VanillaModalCloseElement extends ControlLeaf {
  static override marker = "modal-close";
}
export class VanillaModalPopupElement extends ControlLeaf {
  static override marker = "modal-popup";
  static override kind = "dialog" as const;
  protected override syncControl(): void {
    super.syncControl();
    for (const name of ["aria-labelledby", "aria-describedby"]) {
      const value = this.getAttribute(name);
      if (value) this.control?.setAttribute(name, value);
    }
  }
}

export class VanillaModalElement extends OpenController {
  static observedAttributes = ["open", "default-open", "disabled"];
  #restore: HTMLElement | null = null;
  #dialog: HTMLDialogElement | null = null;
  #onClick = (event: MouseEvent) => {
    const target = event.target as Element;
    if (target.closest(`${VANILLA_MODAL_TRIGGER_TAG} > button`)) {
      this.#restore = target as HTMLElement;
      this.requestOpen(true);
    }
    if (target.closest(`${VANILLA_MODAL_CLOSE_TAG} > button`)) this.requestOpen(false);
    if (target === this.#dialog) {
      const rect = this.#dialog.getBoundingClientRect();
      if (
        event.clientX < rect.left ||
        event.clientX > rect.right ||
        event.clientY < rect.top ||
        event.clientY > rect.bottom
      )
        this.requestOpen(false);
    }
  };
  #onCancel = (event: Event) => {
    event.preventDefault();
    this.requestOpen(false);
  };
  override connectedCallback(): void {
    super.connectedCallback();
    this.addEventListener("click", this.#onClick);
    this.addEventListener("cancel", this.#onCancel);
  }
  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.removeEventListener("click", this.#onClick);
    this.removeEventListener("cancel", this.#onCancel);
  }
  attributeChangedCallback(name: string): void {
    if (name === "open") {
      this.controlled = true;
      this.openState = this.hasAttribute("open");
    }
    this.deferSync();
  }
  protected sync(): void {
    this.initializeOpen();
    const trigger = this.querySelector<HTMLButtonElement>(`${VANILLA_MODAL_TRIGGER_TAG} > button`);
    const popup = this.querySelector<VanillaModalPopupElement>(VANILLA_MODAL_POPUP_TAG);
    const dialog = popup?.querySelector("dialog") ?? null;
    if (!trigger || !popup || !dialog) return;
    this.#dialog = dialog;
    trigger.id ||= nextId(`${VANILLA_MODAL_TRIGGER_TAG}-button`);
    popup.id ||= nextId(VANILLA_MODAL_POPUP_TAG);
    trigger.setAttribute("aria-haspopup", "dialog");
    trigger.setAttribute("aria-expanded", String(this.openState));
    trigger.setAttribute("aria-controls", popup.id);
    trigger.toggleAttribute("disabled", this.disabled);
    trigger.style.cursor = this.disabled ? "not-allowed" : "pointer";
    for (const node of [trigger.parentElement!, popup, dialog]) {
      node.toggleAttribute("data-open", this.openState);
      node.toggleAttribute("data-closed", !this.openState);
      node.toggleAttribute("data-disabled", this.disabled);
    }
    if (this.openState && !dialog.open) {
      if (typeof dialog.showModal === "function") dialog.showModal();
      else dialog.setAttribute("open", "");
    }
    if (!this.openState && dialog.open) {
      if (typeof dialog.close === "function") dialog.close();
      else dialog.removeAttribute("open");
      this.#restore?.focus();
    }
  }
}

const definitions: Array<[string, CustomElementConstructor]> = [
  [VANILLA_MODAL_TAG, VanillaModalElement],
  [VANILLA_MODAL_TRIGGER_TAG, VanillaModalTriggerElement],
  [VANILLA_MODAL_POPUP_TAG, VanillaModalPopupElement],
  [VANILLA_MODAL_CLOSE_TAG, VanillaModalCloseElement],
];
for (const [tag, constructor] of definitions)
  if (!customElements.get(tag)) customElements.define(tag, constructor);

// packages/web-components-solidjs/src/modal.tsx
import { createEffect, onCleanup } from "solid-js";
import { customElement } from "solid-element";
import {
  type ChangeCallback,
  booleanProp,
  classProp,
  createControl,
  emit,
  initializeBooleanProps,
  nextId,
  preserveChildren,
  type SolidElementHost,
  useLightDom,
  watchChildren,
} from "./shared";

export const SOLID_MODAL_TAG = "solid-modal";
export const SOLID_MODAL_TRIGGER_TAG = "solid-modal-trigger";
export const SOLID_MODAL_POPUP_TAG = "solid-modal-popup";
export const SOLID_MODAL_CLOSE_TAG = "solid-modal-close";

interface ControlProps {
  hostClass: string;
  disabled: boolean;
}

const controlProps = { hostClass: classProp, disabled: booleanProp("disabled") };

export const SolidModalTriggerElement = customElement<ControlProps>(
  SOLID_MODAL_TRIGGER_TAG,
  controlProps,
  (props, { element }) =>
    createControl(element as unknown as SolidElementHost, props, "button", "modal-trigger"),
);

export const SolidModalCloseElement = customElement<ControlProps>(
  SOLID_MODAL_CLOSE_TAG,
  controlProps,
  (props, { element }) =>
    createControl(element as unknown as SolidElementHost, props, "button", "modal-close"),
);

interface PopupProps extends ControlProps {
  ariaLabel: string;
  ariaLabelledby: string;
  ariaDescribedby: string;
}

const stringAttribute = (attribute: string) => ({
  value: "",
  attribute,
  notify: false,
  reflect: false,
  parse: false,
});

export const SolidModalPopupElement = customElement<PopupProps>(
  SOLID_MODAL_POPUP_TAG,
  {
    ...controlProps,
    ariaLabel: stringAttribute("aria-label"),
    ariaLabelledby: stringAttribute("aria-labelledby"),
    ariaDescribedby: stringAttribute("aria-describedby"),
  },
  (props, { element }) => {
    const dialog = createControl(
      element as unknown as SolidElementHost,
      props,
      "dialog",
      "modal-popup",
    );
    createEffect(() => {
      for (const [name, value] of [
        ["aria-label", props.ariaLabel],
        ["aria-labelledby", props.ariaLabelledby],
        ["aria-describedby", props.ariaDescribedby],
      ] as const) {
        if (value) dialog.setAttribute(name, value);
        else dialog.removeAttribute(name);
      }
    });
    return dialog;
  },
);

interface ModalProps {
  open: boolean;
  defaultOpen: boolean;
  disabled: boolean;
  onOpenChange: ChangeCallback<boolean>;
}

export const SolidModalElement = customElement<ModalProps>(
  SOLID_MODAL_TAG,
  {
    open: booleanProp("open", false),
    defaultOpen: booleanProp("default-open"),
    disabled: booleanProp("disabled"),
    onOpenChange: null,
  },
  (props, { element }) => {
    useLightDom();
    const host = element as unknown as SolidElementHost & ModalProps;
    preserveChildren(host);
    initializeBooleanProps(host, {
      open: "open",
      defaultOpen: "default-open",
      disabled: "disabled",
    });

    let controlled = host.hasAttribute("open");
    let internalWrite = false;
    let restore: HTMLElement | null = null;
    let currentDialog: HTMLDialogElement | null = null;
    host.addPropertyChangedCallback((name) => {
      if (name === "open" && !internalWrite) controlled = true;
    });
    const setOpen = (open: boolean): void => {
      internalWrite = true;
      host.open = open;
      internalWrite = false;
    };
    setOpen(controlled ? host.hasAttribute("open") : host.hasAttribute("default-open"));

    const requestOpen = (open: boolean): void => {
      if (host.hasAttribute("disabled") || open === Boolean(props.open)) return;
      emit(host, props.onOpenChange, "open-change", "open", open);
      if (!controlled) setOpen(open);
    };
    const sync = (): void => {
      const open = Boolean(props.open);
      const trigger = host.querySelector<HTMLButtonElement>(`${SOLID_MODAL_TRIGGER_TAG} > button`);
      const popup = host.querySelector<HTMLElement>(SOLID_MODAL_POPUP_TAG);
      const dialog = popup?.querySelector<HTMLDialogElement>("dialog") ?? null;
      if (!trigger || !popup || !dialog) return;
      currentDialog = dialog;
      const disabled = host.hasAttribute("disabled");
      trigger.id ||= nextId(`${SOLID_MODAL_TRIGGER_TAG}-button`);
      popup.id ||= nextId(SOLID_MODAL_POPUP_TAG);
      trigger.setAttribute("aria-haspopup", "dialog");
      trigger.setAttribute("aria-expanded", String(open));
      trigger.setAttribute("aria-controls", popup.id);
      trigger.toggleAttribute("disabled", disabled);
      trigger.style.cursor = disabled ? "not-allowed" : "pointer";
      for (const node of [trigger.parentElement!, popup, dialog]) {
        node.toggleAttribute("data-open", open);
        node.toggleAttribute("data-closed", !open);
        node.toggleAttribute("data-disabled", disabled);
      }
      if (open && !dialog.open) {
        if (typeof dialog.showModal === "function") dialog.showModal();
        else dialog.setAttribute("open", "");
      }
      if (!open && dialog.open) {
        if (typeof dialog.close === "function") dialog.close();
        else dialog.removeAttribute("open");
        restore?.focus();
      }
    };
    createEffect(sync);
    watchChildren(host, sync);

    const onClick = (event: MouseEvent): void => {
      const target = event.target as Element;
      if (target.closest(`${SOLID_MODAL_TRIGGER_TAG} > button`)) {
        restore = target as HTMLElement;
        requestOpen(true);
      }
      if (target.closest(`${SOLID_MODAL_CLOSE_TAG} > button`)) requestOpen(false);
      if (target === currentDialog && currentDialog) {
        const rect = currentDialog.getBoundingClientRect();
        if (
          event.clientX < rect.left ||
          event.clientX > rect.right ||
          event.clientY < rect.top ||
          event.clientY > rect.bottom
        )
          requestOpen(false);
      }
    };
    const onCancel = (event: Event): void => {
      event.preventDefault();
      requestOpen(false);
    };
    host.addEventListener("click", onClick);
    host.addEventListener("cancel", onCancel);
    onCleanup(() => {
      host.removeEventListener("click", onClick);
      host.removeEventListener("cancel", onCancel);
    });
  },
);
