// packages/web-components-preact/src/counter.ts
export const PREACT_COUNTER_TAG = "preact-counter";
export const PREACT_COUNTER_MINUS_TAG = "preact-counter-minus-button";
export const PREACT_COUNTER_LABEL_TAG = "preact-counter-label";
export const PREACT_COUNTER_PLUS_TAG = "preact-counter-plus-button";

/** Lenient numeric coercion: non-finite and non-numeric inputs become 0. */
export function parseCounterValue(raw: unknown): number {
  const number =
    typeof raw === "number" ? raw : Number(typeof raw === "string" ? raw.trim() : Number.NaN);

  return Number.isFinite(number) ? Math.trunc(number) : 0;
}

/** Light-DOM controller for the three composed counter children. */
export class PreactCounterElement extends HTMLElement {
  static observedAttributes = ["value"];

  onChange: ((value: number) => void) | null = null;

  #count = 0;
  #controlled = false;
  #assignedValue: number | undefined;
  #assignedDefault: number | undefined;
  #observer: MutationObserver | null = null;

  get defaultValue(): number {
    return this.#assignedDefault ?? parseCounterValue(this.getAttribute("default-value"));
  }

  set defaultValue(next: number) {
    // Defaults are initial state: changing one affects the next connection only.
    this.#assignedDefault = parseCounterValue(next);
  }

  get value(): number {
    return this.#count;
  }

  set value(next: number) {
    this.#controlled = true;
    this.#assignedValue = parseCounterValue(next);
    this.setAttribute("value", String(this.#assignedValue));
  }

  connectedCallback(): void {
    if (this.hasAttribute("value")) {
      this.#controlled = true;
      this.#count = parseCounterValue(this.getAttribute("value"));
    } else if (this.#assignedValue !== undefined) {
      this.#controlled = true;
      this.#count = this.#assignedValue;
      this.setAttribute("value", String(this.#count));
    } else {
      this.#count = this.defaultValue;
    }

    this.addEventListener("click", this.#onClick);
    // Parser-created children can connect after their parent, so additions retry label sync.
    this.#observer = new MutationObserver(() => this.#render());
    this.#observer.observe(this, { childList: true, subtree: true });
    this.#render();
  }

  disconnectedCallback(): void {
    this.removeEventListener("click", this.#onClick);
    this.#observer?.disconnect();
    this.#observer = null;
  }

  attributeChangedCallback(name: string, _old: string | null, next: string | null): void {
    if (name !== "value" || !this.isConnected) {
      return;
    }

    const parsed = parseCounterValue(next);
    if (parsed !== this.#count) {
      this.#controlled = true;
      this.#count = parsed;
      this.#render();
    }
  }

  #onClick = (event: Event): void => {
    const target = event.target as HTMLElement | null;
    const origin = target?.closest?.(`${PREACT_COUNTER_MINUS_TAG},${PREACT_COUNTER_PLUS_TAG}`);

    if (!origin || !this.contains(origin)) {
      return;
    }

    const delta = origin.tagName.toLowerCase() === PREACT_COUNTER_PLUS_TAG ? 1 : -1;
    this.#commit(this.#count + delta);
  };

  #commit(next: number): void {
    if (!this.#controlled) {
      this.#count = next;
      this.#render();
    }

    this.onChange?.(next);
    this.dispatchEvent(
      new CustomEvent("change", {
        bubbles: true,
        composed: true,
        detail: { value: next },
      }),
    );
  }

  #render(): void {
    // Re-query because a label can be inserted or upgraded after the controller.
    this.querySelector(PREACT_COUNTER_LABEL_TAG)?.setAttribute("value", String(this.#count));
  }
}

if (!customElements.get(PREACT_COUNTER_TAG)) {
  customElements.define(PREACT_COUNTER_TAG, PreactCounterElement);
}

// packages/web-components-svelte/src/Counter.svelte
<svelte:options
  customElement={{
    tag: "svelte-counter",
    shadow: "none",
    props: {
      defaultValue: { attribute: "default-value" },
      value: { attribute: "value" },
      onChange: {},
    },
    extend: extendCounter,
  }}
/>

<script module lang="ts">
  const MINUS_TAG = "svelte-counter-minus-button";
  const LABEL_TAG = "svelte-counter-label";
  const PLUS_TAG = "svelte-counter-plus-button";
  const VALUE_INPUT_EVENT = "svelte-counter-value-input";

  function extendCounter(
    customElementConstructor: CustomElementConstructor,
  ): CustomElementConstructor {
    const valueDescriptor = Object.getOwnPropertyDescriptor(
      customElementConstructor.prototype,
      "value",
    );
    const defaultValueDescriptor = Object.getOwnPropertyDescriptor(
      customElementConstructor.prototype,
      "defaultValue",
    );
    const attributeChanged = (
      customElementConstructor.prototype as HTMLElement & {
        attributeChangedCallback(
          name: string,
          oldValue: string | null,
          newValue: string | null,
        ): void;
      }
    ).attributeChangedCallback;

    return class extends customElementConstructor {
      get defaultValue(): unknown {
        return defaultValueDescriptor?.get?.call(this);
      }

      set defaultValue(next: unknown) {
        defaultValueDescriptor?.set?.call(this, parseCounterValue(next));
      }

      get value(): unknown {
        return valueDescriptor?.get?.call(this);
      }

      set value(next: unknown) {
        const parsed = parseCounterValue(next);
        valueDescriptor?.set?.call(this, parsed);
        this.dispatchEvent(
          new CustomEvent(VALUE_INPUT_EVENT, { detail: parsed }),
        );
      }

      attributeChangedCallback(
        name: string,
        oldValue: string | null,
        newValue: string | null,
      ): void {
        attributeChanged.call(this, name, oldValue, newValue);
        if (name === "default-value") {
          defaultValueDescriptor?.set?.call(
            this,
            parseCounterValue(newValue),
          );
        } else if (name === "value") {
          const parsed = parseCounterValue(newValue);
          valueDescriptor?.set?.call(this, parsed);
          this.dispatchEvent(
            new CustomEvent(VALUE_INPUT_EVENT, { detail: parsed }),
          );
        }
      }
    };
  }

  // Empty strings coerce to zero; non-finite values and non-number objects also become zero.
  function parseCounterValue(raw: unknown): number {
    const numeric =
      typeof raw === "number"
        ? raw
        : Number(typeof raw === "string" ? raw.trim() : Number.NaN);
    return Number.isFinite(numeric) ? Math.trunc(numeric) : 0;
  }
</script>

<script lang="ts">
  import { untrack } from "svelte";

  type CounterProps = {
    defaultValue?: unknown;
    value?: unknown;
    onChange?: ((value: number) => void) | null;
  };

  type CounterHost = HTMLElement & {
    value: unknown;
  };

  let {
    defaultValue = 0,
    value = undefined,
    onChange = null,
  }: CounterProps = $props();

  const element = $host() as CounterHost;
  const initialValue = untrack(() => value);
  const initialDefaultValue = untrack(() => defaultValue);
  let controlled =
    element.hasAttribute("value") || initialValue !== undefined;
  const initialCount = parseCounterValue(
    controlled ? initialValue : initialDefaultValue,
  );
  let count = $state(initialCount);
  defaultValue = parseCounterValue(initialDefaultValue);

  // Keep the public getter aligned with the rendered count without reflecting an attribute.
  value = initialCount;

  function publishValue(next: number): void {
    value = next;
  }

  function syncLabel(): void {
    // Re-query because children can arrive or upgrade after their parent connects.
    element.querySelector(LABEL_TAG)?.setAttribute("value", String(count));
  }

  function commit(next: number): void {
    if (!controlled) {
      count = next;
      publishValue(next);
    }

    if (typeof onChange === "function") {
      onChange(next);
    }
    element.dispatchEvent(
      new CustomEvent("change", {
        bubbles: true,
        composed: true,
        detail: { value: next },
      }),
    );
  }

  function handleClick(event: Event): void {
    const target = event.target;
    const origin =
      target instanceof Element
        ? target.closest(`${MINUS_TAG},${PLUS_TAG}`)
        : null;
    if (!origin || !element.contains(origin)) {
      return;
    }

    const delta = origin.tagName.toLowerCase() === PLUS_TAG ? 1 : -1;
    commit(count + delta);
  }

  function handleValueInput(event: Event): void {
    controlled = true;
    count = parseCounterValue((event as CustomEvent<unknown>).detail);
    publishValue(count);
  }

  $effect(() => {
    void count;
    syncLabel();
  });

  // Attach-once wiring: runs as an effect because onMount never fires for
  // light-DOM custom elements under some DOM implementations. No reactive
  // state is read here, so this runs once with cleanup on destroy.
  $effect(() => {
    element.addEventListener("click", handleClick);
    element.addEventListener(VALUE_INPUT_EVENT, handleValueInput);

    // Parser-created children can connect after the controller, including nested content.
    const observer = new MutationObserver(syncLabel);
    observer.observe(element, { childList: true, subtree: true });
    untrack(() => syncLabel());

    return () => {
      element.removeEventListener("click", handleClick);
      element.removeEventListener(VALUE_INPUT_EVENT, handleValueInput);
      observer.disconnect();
    };
  });
</script>
