// packages/web-components-solidjs/src/accordion.tsx
import { createEffect, onCleanup } from "solid-js";
import { customElement } from "solid-element";
import {
  type ChangeCallback,
  booleanProp,
  classProp,
  createControl,
  emit,
  initializeBooleanProps,
  nextId,
  parseJsonStrings,
  preserveChildren,
  reflectedProp,
  type SolidElementHost,
  useLightDom,
  watchChildren,
} from "./shared";

export const SOLID_ACCORDION_TAG = "solid-accordion";
export const SOLID_ACCORDION_ITEM_TAG = "solid-accordion-item";
export const SOLID_ACCORDION_TRIGGER_TAG = "solid-accordion-trigger";
export const SOLID_ACCORDION_PANEL_TAG = "solid-accordion-panel";

interface ItemProps {
  value: string;
  disabled: boolean;
}

export const SolidAccordionItemElement = customElement<ItemProps>(
  SOLID_ACCORDION_ITEM_TAG,
  { value: reflectedProp("", "value"), disabled: booleanProp("disabled") },
  (_props, { element }) => {
    useLightDom();
    const host = element as unknown as SolidElementHost;
    initializeBooleanProps(host, { disabled: "disabled" });
    preserveChildren(host);
  },
);

interface ControlProps {
  hostClass: string;
  disabled: boolean;
}

export const SolidAccordionTriggerElement = customElement<ControlProps>(
  SOLID_ACCORDION_TRIGGER_TAG,
  { hostClass: classProp, disabled: booleanProp("disabled") },
  (props, { element }) =>
    createControl(element as unknown as SolidElementHost, props, "button", "accordion-trigger"),
);

export const SolidAccordionPanelElement = customElement(
  SOLID_ACCORDION_PANEL_TAG,
  (_props, { element }) => {
    useLightDom();
    preserveChildren(element as unknown as SolidElementHost);
  },
);

interface AccordionProps {
  value?: unknown;
  defaultValue?: unknown;
  multiple: boolean;
  disabled: boolean;
  onValueChange: ChangeCallback<string[]>;
}

export const SolidAccordionElement = customElement<AccordionProps>(
  SOLID_ACCORDION_TAG,
  {
    value: reflectedProp<unknown>(undefined, "value"),
    defaultValue: reflectedProp<unknown>(undefined, "default-value"),
    multiple: booleanProp("multiple"),
    disabled: booleanProp("disabled"),
    onValueChange: null,
  },
  (props, { element }) => {
    useLightDom();
    const host = element as unknown as SolidElementHost & AccordionProps;
    preserveChildren(host);
    initializeBooleanProps(host, { multiple: "multiple", disabled: "disabled" });

    let controlled = host.hasAttribute("value");
    let internalWrite = false;
    host.addPropertyChangedCallback((name) => {
      if (name === "value" && !internalWrite) controlled = true;
    });
    const setValue = (value: string[]): void => {
      internalWrite = true;
      host.value = [...value];
      internalWrite = false;
    };
    setValue(
      parseJsonStrings(
        controlled ? props.value : props.defaultValue,
        controlled ? "value" : "defaultValue",
      ),
    );

    const sync = (): void => {
      const value = parseJsonStrings(props.value, "value");
      const items = [...host.querySelectorAll<HTMLElement>(SOLID_ACCORDION_ITEM_TAG)];
      const values = items.map((item) => String((item as HTMLElement & ItemProps).value ?? ""));
      if (values.some((item) => !item) || new Set(values).size !== values.length)
        throw new TypeError("accordion item values must be unique and nonempty");
      if (!host.hasAttribute("multiple") && value.length > 1)
        throw new TypeError("single accordion accepts at most one value");

      for (const item of items) {
        const trigger = item.querySelector<HTMLElement>(`:scope > ${SOLID_ACCORDION_TRIGGER_TAG}`);
        const panel = item.querySelector<HTMLElement>(`:scope > ${SOLID_ACCORDION_PANEL_TAG}`);
        const button = trigger?.querySelector<HTMLButtonElement>("button");
        if (!trigger || !panel || !button) continue;
        const open = value.includes(String((item as HTMLElement & ItemProps).value));
        const disabled = host.hasAttribute("disabled") || item.hasAttribute("disabled");
        button.id ||= nextId(`${SOLID_ACCORDION_TRIGGER_TAG}-button`);
        panel.id ||= nextId(SOLID_ACCORDION_PANEL_TAG);
        button.setAttribute("aria-expanded", String(open));
        button.setAttribute("aria-controls", panel.id);
        button.toggleAttribute("disabled", disabled);
        button.style.cursor = disabled ? "not-allowed" : "pointer";
        panel.setAttribute("role", "region");
        panel.setAttribute("aria-labelledby", button.id);
        panel.hidden = !open;
        for (const node of [item, trigger, panel]) {
          node.toggleAttribute("data-open", open);
          node.toggleAttribute("data-closed", !open);
          node.toggleAttribute("data-disabled", disabled);
        }
      }
    };
    createEffect(sync);
    watchChildren(host, sync);

    const onClick = (event: Event): void => {
      const button = (event.target as Element).closest(`${SOLID_ACCORDION_TRIGGER_TAG} > button`);
      const item = button?.parentElement?.parentElement as (HTMLElement & ItemProps) | null;
      if (
        !item ||
        item.localName !== SOLID_ACCORDION_ITEM_TAG ||
        host.hasAttribute("disabled") ||
        item.hasAttribute("disabled")
      )
        return;
      const current = parseJsonStrings(props.value, "value");
      const next = current.includes(item.value)
        ? current.filter((value) => value !== item.value)
        : host.hasAttribute("multiple")
          ? [...current, item.value]
          : [item.value];
      emit(host, props.onValueChange, "value-change", "value", next);
      if (!controlled) setValue(next);
    };
    host.addEventListener("click", onClick);
    onCleanup(() => host.removeEventListener("click", onClick));
  },
);

// packages/web-components-atomico/src/accordion.tsx
import { type ChangeCallback } from "./shared";
import { nextId, boolAttr, emit, parseJsonStrings, DeferredElement, ControlLeaf } from "./shared";

export const ATOMICO_ACCORDION_TAG = "atomico-accordion";
export const ATOMICO_ACCORDION_ITEM_TAG = "atomico-accordion-item";
export const ATOMICO_ACCORDION_TRIGGER_TAG = "atomico-accordion-trigger";
export const ATOMICO_ACCORDION_PANEL_TAG = "atomico-accordion-panel";

export class AtomicoAccordionItemElement extends HTMLElement {
  get value(): string {
    return this.getAttribute("value") ?? "";
  }
  set value(value: string) {
    if (!value) throw new TypeError("accordion item value must be nonempty");
    this.setAttribute("value", value);
  }
}
export class AtomicoAccordionTriggerElement extends ControlLeaf {
  static override marker = "accordion-trigger";
}
export class AtomicoAccordionPanelElement extends HTMLElement {}

export class AtomicoAccordionElement extends DeferredElement {
  static observedAttributes = ["value", "default-value", "multiple", "disabled"];
  onValueChange: ChangeCallback<string[]> = null;
  #value: string[] = [];
  #controlled = false;
  #initialized = false;
  #onClick = (event: Event) => {
    const button = (event.target as Element).closest(`${ATOMICO_ACCORDION_TRIGGER_TAG} > button`);
    if (!button || !this.contains(button) || this.disabled) return;
    const item = button.parentElement?.parentElement;
    if (!(item instanceof AtomicoAccordionItemElement) || item.hasAttribute("disabled")) return;
    const current = this.#value;
    const next = current.includes(item.value)
      ? current.filter((value) => value !== item.value)
      : this.multiple
        ? [...current, item.value]
        : [item.value];
    emit(this, this.onValueChange, "value-change", "value", next);
    if (!this.#controlled) {
      this.#value = next;
      this.sync();
    }
  };
  get multiple(): boolean {
    return boolAttr(this, "multiple");
  }
  set multiple(value: boolean) {
    this.toggleAttribute("multiple", value);
  }
  get disabled(): boolean {
    return boolAttr(this, "disabled");
  }
  set disabled(value: boolean) {
    this.toggleAttribute("disabled", value);
  }
  get value(): string[] {
    return [...this.#value];
  }
  set value(value: string[]) {
    this.#controlled = true;
    this.setAttribute("value", JSON.stringify(parseJsonStrings(JSON.stringify(value), "value")));
  }
  get defaultValue(): string[] {
    return parseJsonStrings(this.getAttribute("default-value"), "defaultValue");
  }
  set defaultValue(value: string[]) {
    this.setAttribute(
      "default-value",
      JSON.stringify(parseJsonStrings(JSON.stringify(value), "defaultValue")),
    );
  }
  override connectedCallback(): void {
    super.connectedCallback();
    this.addEventListener("click", this.#onClick);
  }
  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.removeEventListener("click", this.#onClick);
  }
  attributeChangedCallback(name: string): void {
    if (name === "value") {
      this.#controlled = true;
      this.#value = parseJsonStrings(this.getAttribute("value"), "value");
    }
    this.deferSync();
  }
  protected sync(): void {
    const items = [
      ...this.querySelectorAll<AtomicoAccordionItemElement>(ATOMICO_ACCORDION_ITEM_TAG),
    ];
    const values = items.map((item) => item.value);
    if (values.some((value) => !value) || new Set(values).size !== values.length)
      throw new TypeError("accordion item values must be unique and nonempty");
    if (!this.#initialized) {
      this.#initialized = true;
      if (!this.#controlled) this.#value = this.defaultValue;
    }
    if (!this.multiple && this.#value.length > 1)
      throw new TypeError("single accordion accepts at most one value");
    for (const item of items) {
      const trigger = item.querySelector<AtomicoAccordionTriggerElement>(
        `:scope > ${ATOMICO_ACCORDION_TRIGGER_TAG}`,
      );
      const panel = item.querySelector<AtomicoAccordionPanelElement>(
        `:scope > ${ATOMICO_ACCORDION_PANEL_TAG}`,
      );
      const button = trigger?.querySelector("button");
      if (!trigger || !panel || !button) continue;
      const open = this.#value.includes(item.value);
      button.id ||= nextId(`${ATOMICO_ACCORDION_TRIGGER_TAG}-button`);
      panel.id ||= nextId(ATOMICO_ACCORDION_PANEL_TAG);
      button.setAttribute("aria-expanded", String(open));
      button.setAttribute("aria-controls", panel.id);
      button.toggleAttribute("disabled", this.disabled || item.hasAttribute("disabled"));
      button.style.cursor = button.hasAttribute("disabled") ? "not-allowed" : "pointer";
      panel.setAttribute("role", "region");
      panel.setAttribute("aria-labelledby", button.id);
      panel.hidden = !open;
      item.toggleAttribute("data-open", open);
      item.toggleAttribute("data-closed", !open);
      trigger.toggleAttribute("data-open", open);
      trigger.toggleAttribute("data-closed", !open);
      panel.toggleAttribute("data-open", open);
      panel.toggleAttribute("data-closed", !open);
      for (const node of [item, trigger, panel]) {
        node.toggleAttribute("data-disabled", this.disabled || item.hasAttribute("disabled"));
      }
    }
  }
}

export const accordionDefinitions: ReadonlyArray<readonly [string, CustomElementConstructor]> = [
  [ATOMICO_ACCORDION_TAG, AtomicoAccordionElement],
  [ATOMICO_ACCORDION_ITEM_TAG, AtomicoAccordionItemElement],
  [ATOMICO_ACCORDION_TRIGGER_TAG, AtomicoAccordionTriggerElement],
  [ATOMICO_ACCORDION_PANEL_TAG, AtomicoAccordionPanelElement],
];
