// packages/web-components-solidjs/src/toggle-checkbox.tsx
import { createEffect, onCleanup } from "solid-js";
import { customElement } from "solid-element";
import {
  type ChangeCallback,
  booleanProp,
  classProp,
  emit,
  initializeBooleanProps,
  reflectedProp,
  type SolidElementHost,
  useLightDom,
} from "./shared";

export const SOLID_TOGGLE_CHECKBOX_TAG = "solid-toggle-checkbox";

interface CheckboxProps {
  checked: boolean;
  defaultChecked: boolean;
  indeterminate: boolean;
  disabled: boolean;
  readOnly: boolean;
  required: boolean;
  name: string;
  value: string;
  form: string;
  ariaLabel: string;
  hostClass: string;
  onCheckedChange: ChangeCallback<boolean>;
}

export const SolidToggleCheckboxElement = customElement<CheckboxProps>(
  SOLID_TOGGLE_CHECKBOX_TAG,
  {
    checked: booleanProp("checked", false),
    defaultChecked: booleanProp("default-checked"),
    indeterminate: booleanProp("indeterminate"),
    disabled: booleanProp("disabled"),
    readOnly: booleanProp("readonly"),
    required: booleanProp("required"),
    name: reflectedProp("", "name"),
    value: reflectedProp("", "value"),
    form: reflectedProp("", "form"),
    ariaLabel: reflectedProp("", "aria-label"),
    hostClass: classProp,
    onCheckedChange: null,
  },
  (props, { element }) => {
    useLightDom();
    const host = element as unknown as SolidElementHost & CheckboxProps;
    const input = document.createElement("input");
    input.type = "checkbox";
    initializeBooleanProps(host, {
      checked: "checked",
      defaultChecked: "default-checked",
      indeterminate: "indeterminate",
      disabled: "disabled",
      readOnly: "readonly",
      required: "required",
    });

    let controlled = host.hasAttribute("checked");
    let internalWrite = false;
    host.addPropertyChangedCallback((name) => {
      if (name === "checked" && !internalWrite) controlled = true;
    });
    const setChecked = (checked: boolean): void => {
      internalWrite = true;
      host.checked = checked;
      internalWrite = false;
    };
    setChecked(controlled ? host.hasAttribute("checked") : host.hasAttribute("default-checked"));

    const sync = (): void => {
      const checked = Boolean(props.checked);
      const disabled = host.hasAttribute("disabled");
      input.className = props.hostClass ? `toggle-checkbox ${props.hostClass}` : "toggle-checkbox";
      input.dataset.testid = host.localName;
      input.style.cursor = disabled ? "not-allowed" : "pointer";
      input.checked = checked;
      input.indeterminate = host.hasAttribute("indeterminate");
      input.disabled = disabled;
      input.readOnly = host.hasAttribute("readonly");
      input.required = host.hasAttribute("required");
      for (const [name, value] of [
        ["name", props.name],
        ["value", props.value],
        ["form", props.form],
        ["aria-label", props.ariaLabel],
      ] as const) {
        if (value) input.setAttribute(name, value);
        else input.removeAttribute(name);
      }
      for (const node of [host, input]) {
        node.toggleAttribute("data-checked", checked);
        node.toggleAttribute("data-unchecked", !checked);
        node.toggleAttribute("data-disabled", disabled);
      }
    };
    createEffect(sync);

    const onChange = (): void => {
      if (host.hasAttribute("disabled") || host.hasAttribute("readonly")) {
        sync();
        return;
      }
      const next = input.checked;
      emit(host, props.onCheckedChange, "checked-change", "checked", next);
      if (controlled) sync();
      else setChecked(next);
    };
    input.addEventListener("change", onChange);
    onCleanup(() => input.removeEventListener("change", onChange));

    return input;
  },
);

// packages/web-components-atomico/src/toggle-checkbox.tsx
import { type ChangeCallback } from "./shared";
import { boolAttr, emit, upgradeProperties } from "./shared";

export const ATOMICO_TOGGLE_CHECKBOX_TAG = "atomico-toggle-checkbox";
export class AtomicoToggleCheckboxElement extends HTMLElement {
  static observedAttributes = [
    "checked",
    "default-checked",
    "indeterminate",
    "disabled",
    "readonly",
    "required",
    "name",
    "value",
    "form",
    "aria-label",
  ];
  onCheckedChange: ChangeCallback<boolean> = null;
  #input: HTMLInputElement | null = null;
  #checked = false;
  #controlled = false;
  #initialized = false;
  #observer: MutationObserver | null = null;
  get checked(): boolean {
    return this.#checked;
  }
  set checked(value: boolean) {
    this.#controlled = true;
    this.toggleAttribute("checked", value);
  }
  get defaultChecked(): boolean {
    return boolAttr(this, "default-checked");
  }
  set defaultChecked(value: boolean) {
    this.toggleAttribute("default-checked", value);
  }
  get indeterminate(): boolean {
    return boolAttr(this, "indeterminate");
  }
  set indeterminate(value: boolean) {
    this.toggleAttribute("indeterminate", value);
  }
  get disabled(): boolean {
    return boolAttr(this, "disabled");
  }
  set disabled(value: boolean) {
    this.toggleAttribute("disabled", value);
  }
  get readOnly(): boolean {
    return boolAttr(this, "readonly");
  }
  set readOnly(value: boolean) {
    this.toggleAttribute("readonly", value);
  }
  connectedCallback(): void {
    upgradeProperties(this, ["checked", "defaultChecked", "indeterminate", "disabled", "readOnly"]);
    if (!this.#input) {
      this.#input = document.createElement("input");
      this.#input.type = "checkbox";
      this.replaceChildren(this.#input);
    }
    this.#input.addEventListener("change", this.#onChange);
    this.#observer = new MutationObserver(() => this.#sync());
    this.#observer.observe(this, { attributes: true, attributeFilter: ["class"], childList: true });
    this.#sync();
  }
  disconnectedCallback(): void {
    this.#input?.removeEventListener("change", this.#onChange);
    this.#observer?.disconnect();
  }
  attributeChangedCallback(name: string): void {
    if (name === "checked") {
      this.#controlled = true;
      this.#checked = this.hasAttribute("checked");
    }
    this.#sync();
  }
  #onChange = () => {
    if (!this.#input || this.disabled || this.readOnly) {
      this.#sync();
      return;
    }
    const next = this.#input.checked;
    emit(this, this.onCheckedChange, "checked-change", "checked", next);
    if (!this.#controlled) this.#checked = next;
    this.#sync();
  };
  #sync(): void {
    if (!this.#input) return;
    if (!this.#initialized) {
      this.#initialized = true;
      if (!this.#controlled) this.#checked = this.defaultChecked;
    }
    const input = this.#input;
    input.className = `toggle-checkbox${this.className ? ` ${this.className}` : ""}`;
    input.dataset.testid = this.localName;
    input.style.cursor = this.disabled ? "not-allowed" : "pointer";
    input.checked = this.#checked;
    input.indeterminate = this.indeterminate;
    input.disabled = this.disabled;
    input.readOnly = this.readOnly;
    input.required = boolAttr(this, "required");
    for (const name of ["name", "value", "form", "aria-label"]) {
      const value = this.getAttribute(name);
      if (value === null) input.removeAttribute(name);
      else input.setAttribute(name, value);
    }
    this.toggleAttribute("data-checked", this.#checked);
    this.toggleAttribute("data-unchecked", !this.#checked);
    this.toggleAttribute("data-disabled", this.disabled);
    input.toggleAttribute("data-checked", this.#checked);
    input.toggleAttribute("data-unchecked", !this.#checked);
    input.toggleAttribute("data-disabled", this.disabled);
  }
}

export const toggleCheckboxDefinitions: ReadonlyArray<readonly [string, CustomElementConstructor]> =
  [[ATOMICO_TOGGLE_CHECKBOX_TAG, AtomicoToggleCheckboxElement]];
